### ISSUE TITLE
Search Node on Individual Pathway

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/pathways-search#108] opened 2017-07-12 19:28 UTC
Glycolysis is a pathway that tends to be presented in a linear fashion. Because it isn't in the current app, it is hard to orient oneself of the chain of events that is occurring. It might be useful to include a search that would highlight a node of interest by a user within a particular pathway.

**Comment by jvwong** [comment] 2017-09-27 14:22
Closing, duplicate of #130

**Closed as completed by jvwong** 2017-09-27 14:22 UTC
Labels: enhancement, Priority : High
